[phases.setup]
nixPkgs = [
  "openssl",
  "postgresql_16",
  "gcc",
  "python310",
  "python310Packages.pip"
]

[phases.build]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt",
  "python manage.py collectstatic --noinput"
]

[phases.start]
cmd = "python manage.py migrate && gunicorn myproject.wsgi:application --workers=3 --threads=2 --bind 0.0.0.0:${PORT}"

[checks]
healthcheck = "/health/"
