[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "openssl", "postgresql_16"]

[phases.install]
cmd = "pip install -r requirements.txt"

[phases.build]
cmd = "python manage.py collectstatic --noinput"

[phases.start]
cmd = "gunicorn novaera.wsgi:application --bind 0.0.0.0:${PORT} --workers=3"
