# Generated by Django 4.0.3 on 2025-11-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter_email',
            name='subscribed',
            field=models.BooleanField(default=True, verbose_name='subscribed'),
        ),
    ]
