# Generated by Django 4.0.3 on 2025-11-12 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_alter_newsletter_email_subscribed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter_email',
            name='subscribed',
        ),
    ]
