# Generated by Django 4.0.3 on 2025-11-12 16:01

import banda_contratacion.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contratacion_datos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toda_banda', models.BooleanField(default=True, validators=[banda_contratacion.models.conxunto_validation], verbose_name='toda_banda')),
                ('cuarteto', models.BooleanField(default=False, validators=[banda_contratacion.models.conxunto_validation], verbose_name='cuarteto')),
                ('terceto_opcion_1', models.BooleanField(default=False, validators=[banda_contratacion.models.conxunto_validation], verbose_name='terceto_opcion_1')),
                ('terceto_opcion_2', models.BooleanField(default=False, validators=[banda_contratacion.models.conxunto_validation], verbose_name='terceto_opcion_2')),
                ('duo_opcion_1', models.BooleanField(default=False, validators=[banda_contratacion.models.conxunto_validation], verbose_name='duo_opcion_1')),
                ('duo_opcion_2', models.BooleanField(default=False, validators=[banda_contratacion.models.conxunto_validation], verbose_name='duo_opcion_2')),
                ('conxunto', models.BooleanField(default=False, validators=[banda_contratacion.models.conxunto_validation, banda_contratacion.models.enviar_mensaxe_error, banda_contratacion.models.limpiar_lista], verbose_name='solista')),
                ('tipo_evento', models.CharField(choices=[('festival', 'Festival'), ('festa_aldea', 'Festa aldea'), ('voda', 'Voda'), ('bautizo', 'Bautizo'), ('aniversario', 'Aniversario'), ('funeral', 'Funeral'), ('outros', 'Outros')], max_length=11)),
                ('data_evento', models.DateField()),
                ('lugar_evento', models.CharField(max_length=255)),
                ('nome', models.CharField(max_length=255)),
                ('teléfono', models.IntegerField(validators=[banda_contratacion.models.telephone_number_validation])),
                ('correo_electrónico', models.EmailField(max_length=255, validators=[banda_contratacion.models.email_validation_contratacion])),
                ('mais_info', models.TextField(blank=True)),
                ('data_rexistro', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('contestado', models.BooleanField(default=False, verbose_name='contestado')),
            ],
        ),
    ]
