# Generated by Django 4.0.3 on 2025-11-12 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='entradas_modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('apelidos', models.CharField(max_length=255)),
                ('correo_electrónico_entradas', models.EmailField(max_length=255)),
                ('numero_entradas', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('data_rexistro', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
            ],
        ),
    ]
