# Generated by Django 4.0.3 on 2023-08-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faladoiras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faladoiras',
            name='you_tube_iframe',
            field=models.CharField(default='Inclúe o iframe do vídeo de youtube', max_length=120),
        ),
    ]
