# Generated by Django 4.0.3 on 2023-08-19 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faladoiras', '0002_faladoiras_you_tube_iframe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faladoiras',
            name='you_tube_iframe',
        ),
        migrations.AddField(
            model_name='faladoiras',
            name='youtube_link',
            field=models.CharField(default='Inclúe o iframe do vídeo de youtube', max_length=1000),
        ),
    ]
