# Generated by Django 4.0.3 on 2023-12-14 09:46

import ckeditor.fields
import datetime
from django.db import migrations, models
import faladoiras.models


class Migration(migrations.Migration):

    dependencies = [
        ('faladoiras', '0003_remove_faladoiras_you_tube_iframe_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faladoiras',
            options={'ordering': ['-faladoiras_date']},
        ),
        migrations.AlterField(
            model_name='faladoiras',
            name='faladoiras_content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faladoiras',
            name='faladoiras_date',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Data_Non_completar'),
        ),
        migrations.AlterField(
            model_name='faladoiras',
            name='faladoiras_image_persoa',
            field=models.ImageField(blank=True, null=True, upload_to=faladoiras.models.upload_image_path, verbose_name='Foto da persoa entrevistada'),
        ),
        migrations.AlterField(
            model_name='faladoiras',
            name='faladoiras_persoa',
            field=models.CharField(max_length=120, verbose_name='Nome da persoa entrevistada'),
        ),
        migrations.AlterField(
            model_name='faladoiras',
            name='faladoiras_resumen_persoa',
            field=models.TextField(verbose_name='Breve resume do entrevistado'),
        ),
        migrations.AlterField(
            model_name='faladoiras',
            name='youtube_link',
            field=models.CharField(max_length=1000),
        ),
    ]
