"""
Django settings for NovaEra project.

Generated by 'django-admin startproject' using Django 3.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from importlib.resources import Resource
from pathlib import Path
import os

from decouple import config

#UN VÍDEO MUI INTERESANTE PARA FACER O DEPLOY INTO HEROKU
# https://www.youtube.com/watch?v=5d8AQFF0Ot0&t=555s

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
print ("A ruta do BaseDir", BASE_DIR)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-n^&le##@@+9%tc!s*8rjq4-l_x7yezo1j(745nln0x@%(vv&)!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#Eiqui a parte de ter o meu host local (127.0.0.1) engado tamén o host de heroku
ALLOWED_HOSTS = []
#ALLOWED_HOSTS = ['*']
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #Esto é para implementar os botóns de share no blog
    'django_social_share',
    'widget_tweaks',
    #my apps
    'artigos',
    'banda_contratacion',
    'newsletter',
    'faladoiras',
    #Installing the Amazon Web Service Storage
    'storages',
    #Para implementar o rich text no cuadro do text field dos artículos
    #https://www.geeksforgeeks.org/richtextfield-django-models/
    'ckeditor',
    'ckeditor_uploader',
    'entradas'
]

# ESto é para o ckeditor que me estaba dando error
CKEDITOR_UPLOAD_PATH = 'content/ckeditor/'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #Incluir eiqui o whitenoise para os archivos estáticos unha vez que estos se suban a heroku
    'whitenoise.middleware.WhiteNoiseMiddleware'
]

ROOT_URLCONF = 'NovaEra.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'NovaEra/templates',
                 BASE_DIR / 'artigos/templates',
                 BASE_DIR / 'banda_contratacion/templates/',
                 BASE_DIR / 'entradas/templates/',
                 BASE_DIR / 'faladoiras/templates/',
                 ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'NovaEra.wsgi.application'

#Esto é para que non me de error a hora de completar os formularios no móbil nin en ningún outro dispositivo
CSRF_TRUSTED_ORIGINS = ['https://novaera.gal', 'https://*.novaera.gal', 'https://novaera.up.railway.app', 'https://novaera.up.railway.app*']
CSRF_COOKIE_SECURE = False


#-------------------start---------database local configuration---------------------
# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases
# No caso de que as tablas non se che creen cando fas makemigrations e migrate utiliza este
# comando: "python manage.py migrate --run-syncdb"

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}
#-------------------end---------database local configuration---------------------

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'gl-ES'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'

#IMPORTANTE: o STATICFILES_DIRS é para indicar onde metes os arquivos estáticos
STATICFILES_DIRS=[
   BASE_DIR / "NovaEra/static/"
]

#Esto é para asignarlle un sitio a carpeta que se crea cando se fai o "python manage.py collectstatic"
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

#MEDIA FILES: Estes son arquivos que suben os usuarios da web
MEDIA_ROOT = os.path.join(BASE_DIR)

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


#SMTP Configuration para envío de emails
# https://www.youtube.com/watch?v=sFPcd6myZrY
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
