# Generated by Django 4.0.3 on 2025-11-12 16:00

import artigos.models
import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='autores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_autor', models.ImageField(blank=True, null=True, upload_to=artigos.models.upload_image_path)),
                ('name_autor', models.CharField(blank=True, max_length=120, null=True)),
                ('description_autor', models.TextField()),
                ('social_media', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='artigos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=artigos.models.upload_image_path)),
                ('artigos_title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Deixar_en_blanco')),
                ('artigos_summary', models.TextField()),
                ('artigos_content', ckeditor.fields.RichTextField()),
                ('artigos_date', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='artigos', to='artigos.autores')),
            ],
            options={
                'ordering': ['-artigos_date'],
            },
        ),
        migrations.CreateModel(
            name='artigo_comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('correo_electrónico', models.EmailField(max_length=255, validators=[artigos.models.email_validation])),
                ('comentario', models.TextField()),
                ('date_added', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('artigo_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='artigos.artigos')),
            ],
            options={
                'ordering': ['date_added'],
            },
        ),
    ]
