# Generated by Django 4.0.3 on 2025-12-18 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0001_initial'),
    ]

    operations = [
    ]
